// packages/features/src/documents/DocumentPublishPanel.tsx
import { useCallback, useMemo, useState } from 'react';
import type { DocumentPublicationResponse } from '@den-web/api/client';
import { previewDocumentPublication, publishDocument } from '@den-web/api/client';
import type { Document } from '@den-web/api/types';

interface Props {
  document: Document;
  onClose: () => void;
}

type PublishState = 'idle' | 'previewing' | 'ready' | 'publishing' | 'published' | 'error';

export function DocumentPublishPanel({ document, onClose }: Props) {
  const [overwrite, setOverwrite] = useState(false);
  const [state, setState] = useState<PublishState>('idle');
  const [error, setError] = useState<string | null>(null);
  const [preview, setPreview] = useState<DocumentPublicationResponse | null>(null);
  const [published, setPublished] = useState<DocumentPublicationResponse | null>(null);

  const request = useMemo(() => ({
    source: {
      project_id: document.project_id,
      document_project_id: document.project_id,
      document_slug: document.slug,
    },
    options: {
      tags: document.tags ?? [],
      overwrite,
    },
    requested_by: 'den-web',
    document: {
      title: document.title,
      slug: document.slug,
      markdown: document.content,
      updated_at: document.updated_at,
    },
  }), [document, overwrite]);

  const handlePreview = useCallback(async () => {
    setState('previewing');
    setError(null);
    setPublished(null);
    try {
      const response = await previewDocumentPublication(request);
      setPreview(response);
      setState('ready');
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setState('error');
    }
  }, [request]);

  const handlePublish = useCallback(async () => {
    setState('publishing');
    setError(null);
    try {
      const response = await publishDocument(request);
      setPublished(response);
      setPreview(response);
      setState('published');
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setState('error');
    }
  }, [request]);

  const busy = state === 'previewing' || state === 'publishing';
  const canPublish = preview !== null && (state === 'ready' || state === 'published' || state === 'error');

  return (
    <div className="document-publish-panel" role="region" aria-label="Document blog publishing">
      <div className="document-publish-header">
        <div>
          <h3>Share via blog</h3>
        </div>
        <button
          type="button"
          className="discussion-reply-cancel"
          onClick={onClose}
          disabled={busy}
          aria-label="Close publish panel"
        >
          x
        </button>
      </div>

      <label className="document-publish-toggle">
        <input
          type="checkbox"
          checked={overwrite}
          onChange={event => {
            setOverwrite(event.target.checked);
            setPreview(null);
            setPublished(null);
            setError(null);
            setState('idle');
          }}
          disabled={busy}
        />
        Overwrite an existing generated post at the same path
      </label>

      <div className="document-publish-actions">
        <button
          type="button"
          className="detail-action"
          onClick={() => void handlePreview()}
          disabled={busy}
        >
          {state === 'previewing' ? 'Previewing...' : 'Preview'}
        </button>
        <button
          type="button"
          className="detail-action detail-action-primary"
          onClick={() => void handlePublish()}
          disabled={busy || !canPublish}
        >
          {state === 'publishing' ? 'Publishing...' : 'Publish'}
        </button>
      </div>

      {error && <div className="detail-error" role="alert">Publish failed: {error}</div>}
      {published && <PublishedResult result={published} />}
      {preview && <PreviewResult result={preview} />}
    </div>
  );
}

function PublishedResult({ result }: { result: DocumentPublicationResponse }) {
  return (
    <div className="detail-info document-publish-result" role="status">
      Published to <a href={result.public_url} target="_blank" rel="noreferrer">{result.public_url}</a>
      {result.git_commit && <span className="document-publish-commit">commit {result.git_commit.slice(0, 12)}</span>}
    </div>
  );
}

function PreviewResult({ result }: { result: DocumentPublicationResponse }) {
  return (
    <div className="document-publish-preview">
      <dl className="detail-meta">
        <dt>Post path</dt>
        <dd>{result.post_path}</dd>
        <dt>Public URL</dt>
        <dd>{result.public_url}</dd>
      </dl>
      {result.warnings && result.warnings.length > 0 && (
        <div className="document-publish-warnings">{result.warnings.join(' ')}</div>
      )}
      {result.preview_markdown && (
        <pre className="document-publish-markdown">{result.preview_markdown}</pre>
      )}
    </div>
  );
}

// libs/feature-documents/src/lib/document-publish-panel.component.ts
import { Component, computed, EventEmitter, inject, Input, Output } from '@angular/core';
import type { DenDocPublishRequest, DenDocumentDetail } from '@den-web/protocol';
import { DOCUMENT_PUBLISH_STORE, stateValue } from '@den-web/store';

@Component({
  selector: 'den-document-publish-panel',
  standalone: true,
  styles: [
    `
      :host {
        display: block;
      }

      .publish-panel {
        border: 1px solid var(--den-border);
        border-radius: 8px;
        display: grid;
        gap: 12px;
        padding: 12px;
      }

      .publish-head,
      .actions,
      .toggle {
        align-items: center;
        display: flex;
        gap: 10px;
      }

      .publish-head {
        justify-content: space-between;
      }

      h3 {
        font-size: var(--den-font-size-md);
        margin: 0;
      }

      .toggle {
        color: var(--den-muted);
        font-size: var(--den-font-size-md);
      }

      button {
        appearance: none;
        background: var(--den-input);
        border: 1px solid var(--den-border);
        border-radius: 6px;
        color: var(--den-text);
        cursor: pointer;
        font: inherit;
        min-height: 32px;
        padding: 0 10px;
      }

      button:hover,
      button:focus-visible {
        background: var(--den-hover);
        border-color: var(--den-border-strong);
        outline: none;
      }

      button:disabled {
        cursor: not-allowed;
        opacity: 0.58;
      }

      .primary {
        background: var(--den-accent);
        border-color: var(--den-accent);
        color: var(--den-accent-contrast);
      }

      .close {
        min-width: 32px;
        padding: 0;
      }

      .result,
      .preview {
        border: 1px solid var(--den-border);
        border-radius: 6px;
        display: grid;
        gap: 8px;
        padding: 10px;
      }

      .result a {
        color: var(--den-accent);
      }

      .commit,
      .muted,
      .warning,
      .error {
        color: var(--den-muted);
        font-size: var(--den-font-size-sm);
      }

      .warning {
        color: var(--den-warning);
      }

      .error {
        color: var(--den-danger);
      }

      dl {
        display: grid;
        gap: 4px 10px;
        grid-template-columns: max-content minmax(0, 1fr);
        margin: 0;
      }

      dt {
        color: var(--den-muted);
        font-size: var(--den-font-size-xs);
        font-weight: 700;
        text-transform: uppercase;
      }

      dd {
        margin: 0;
        min-width: 0;
        overflow-wrap: anywhere;
      }

      pre {
        background: var(--den-input);
        border-radius: 6px;
        margin: 0;
        max-height: 260px;
        overflow: auto;
        padding: 10px;
        white-space: pre-wrap;
      }
    `,
  ],
  template: `
    @if (document) {
      <div class="publish-panel" role="region" aria-label="Document blog publishing">
        <div class="publish-head">
          <h3>Share via blog</h3>
          <button type="button" class="close" aria-label="Close share panel" [disabled]="busy()" (click)="requestClose()">x</button>
        </div>

        <label class="toggle">
          <input type="checkbox" [checked]="overwrite()" [disabled]="busy()" (change)="setOverwrite($event)" />
          Overwrite an existing generated post at the same path
        </label>

        <div class="actions">
          <button type="button" [disabled]="busy()" (click)="preview()">{{ previewLabel() }}</button>
          <button type="button" class="primary" [disabled]="busy() || !canPublish()" (click)="publish()">{{ publishLabel() }}</button>
        </div>

        @if (errorText()) {
          <div class="error" role="alert">Publish failed: {{ errorText() }}</div>
        }

        @if (published()) {
          @let result = published();
          @if (result) {
            <div class="result" role="status">
              @if (result.public_url) {
                <span>Published to <a [href]="result.public_url" target="_blank" rel="noreferrer">{{ result.public_url }}</a></span>
              } @else {
                <span>Published</span>
              }
              @if (result.git_commit) {
                <span class="commit">commit {{ shortCommit(result.git_commit) }}</span>
              }
            </div>
          }
        }

        @if (previewResult()) {
          @let result = previewResult();
          @if (result) {
            <div class="preview">
              <dl>
                <dt>Post path</dt>
                <dd>{{ result.post_path || 'pending' }}</dd>
                <dt>Public URL</dt>
                <dd>{{ result.public_url || 'pending' }}</dd>
              </dl>
              @if ((result.warnings ?? []).length > 0) {
                <div class="warning">{{ (result.warnings ?? []).join(' ') }}</div>
              }
              @if (result.preview_markdown) {
                <pre>{{ result.preview_markdown }}</pre>
              }
            </div>
          }
        }
      </div>
    }
  `,
})
export class DocumentPublishPanelComponent {
  private readonly store = inject(DOCUMENT_PUBLISH_STORE);

  @Input() document: DenDocumentDetail | null = null;
  @Output() readonly close = new EventEmitter<void>();

  protected readonly overwrite = this.store.overwrite;
  protected readonly previewResult = computed(() => stateValue(this.store.previewResult()) ?? null);
  protected readonly published = computed(() => stateValue(this.store.publishedResult()) ?? null);
  protected readonly busy = computed(() => this.store.previewResult().kind === 'loading' || this.store.publishedResult().kind === 'loading');
  protected readonly canPublish = computed(() => this.previewResult() !== null);
  protected readonly errorText = computed(() => {
    const previewState = this.store.previewResult();
    if (previewState.kind === 'error') return previewState.error.message;
    const publishedState = this.store.publishedResult();
    return publishedState.kind === 'error' ? publishedState.error.message : null;
  });
  protected readonly previewLabel = computed(() => this.store.previewResult().kind === 'loading' ? 'Previewing...' : 'Preview');
  protected readonly publishLabel = computed(() => this.store.publishedResult().kind === 'loading' ? 'Publishing...' : 'Publish');

  protected setOverwrite(event: Event): void {
    const target = event.target;
    if (target instanceof HTMLInputElement) this.store.setOverwrite(target.checked);
  }

  protected preview(): void {
    const request = this.request();
    if (request) void this.store.preview(request);
  }

  protected publish(): void {
    const request = this.request();
    if (request) void this.store.publish(request);
  }

  protected requestClose(): void {
    this.store.reset();
    this.close.emit();
  }

  protected shortCommit(commit: string): string {
    return commit.slice(0, 12);
  }

  private request(): DenDocPublishRequest | null {
    const document = this.document;
    if (!document) return null;
    return {
      source: {
        project_id: document.project_id,
        document_project_id: document.project_id,
        document_slug: document.slug,
      },
      options: {
        tags: document.tags ?? [],
        overwrite: this.overwrite(),
      },
      requested_by: 'den-web',
    };
  }
}
